export const DESTINATIONS_LOADING = 'DESTINATIONS_LOADING';
export const ADD_DESTINATIONS = 'ADD_DESTINATIONS';
export const DESTINATIONS_FAILED = 'DESTINATIONS_FAILED';

export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';

export const PROMOTIONS_LOADING = 'PROMOTIONS_LOADING';
export const ADD_PROMOTIONS = 'ADD_PROMOTIONS';
export const PROMOTIONS_FAILED = 'PROMOTIONS_FAILED';

export const PARTNERS_LOADING = 'PARTNERS_LOADING';
export const ADD_PARTNERS = 'ADD_PARTNERS';
export const PARTNERS_FAILED = 'PARTNERS_FAILED';

export const ADD_FAVORITE = 'ADD_FAVORITE';

export const ADD_COMMENT = 'ADD_COMMENT';

export const DELETE_FAVORITE = 'DELETE_FAVORITE'; 
